[package]
name = "thirdlang"
version = "0.1.0"
description = "An object-oriented programming language with classes, methods, and explicit memory management"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
inkwell = { workspace = true, optional = true }
pest = { workspace = true, optional = true }
pest_derive = { workspace = true, optional = true }
winnow = { version = "0.7.14", optional = true }
clap = { version = "4.5.54", features = ["derive"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "thirdlang"
path = "src/main.rs"

[features]
pest_parser = ["pest", "pest_derive"]
winnow_parser = ["winnow"]
llvm_backend = ["inkwell"]

# Uncomment for rustanalyzer to work on a specific feature
# default = ["pest_parser", "llvm_backend"]
default = ["winnow_parser", "llvm_backend"]
