cargo-features = ["profile-rustflags"]

[workspace]
default-members = ["crates/firstlang"]
members = ["crates/*"]
resolver = "3"

[workspace.lints.rust]
unused_must_use = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -2 }

# Pedantic allows
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
inline_always = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
new_without_default = "allow"
return_self_not_must_use = "allow"

# Nursery allows
too_long_first_doc_paragraph = "allow"

[profile.dev.package."*"]
codegen-units = 1
opt-level = 2
rustflags = ["-C", "target-cpu=native"]

[profile.release]
rustflags = ["-C", "target-cpu=native"]
