[package]
name = "secondlang"
version = "0.1.0"
description = "A typed, compiled programming language with LLVM backend"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
inkwell = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
clap = { version = "4.5.54", features = ["derive"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "secondlang"
path = "src/main.rs"
