[package]
name = "calculator"
version = "0.1.0"
description = "A simple calculator language for learning compiler basics"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
inkwell = { workspace = true, optional = true}
pest = { workspace = true }
pest_derive = { workspace = true }
rustyline = "17.0.2"
cfg-if = "1.0.4"

[lib]
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/repl.rs"
test = false

[features]
tree_walk = []
bytecode = []
jit_llvm = ["inkwell"]

# Uncomment for rustanalyzer to work on a specific feature
# default = ["tree_walk"]
# default = ["bytecode"]
default = ["jit_llvm"]
