[package]
name = "firstlang"
version = "0.1.0"
description = "A simple interpreted programming language for learning"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "firstlang"
path = "src/main.rs"
